baseURL = 'https://seriefolkets-stora-pris.vercel.app'
languageCode = 'sv-se'
title = 'SERIEFOLKETS STORA PRIS'
theme = 'blowfish'
defaultContentLanguage = "sv"
defaultContentLanguageInSubdir = false

[menu]

 [[menu.main]]
  name = "Logg"
  url = "/Logg/"
  weight = 1

  [[menu.main]]
  name = "Foton från 2024"
  url = "logg/foton2024/"
  weight = 1
  parent = "Logg"


  [[menu.main]]
  name = "Frågor"
  url = "/fragor/"
  weight = 2

  [[menu.main]]
  name = "Kategorier"
  url = "/kategorier/"
  weight = 3

[[menu.main]]
name = "Nomineringar"
url = ""          # Ingen indexsida
weight = 4
identifier = "Nomineringar"

[[menu.main]]
name = "Nomineringar 2024"
url = "/nomineringar/nomineringar2024/"
weight = 1
parent = "Nomineringar"

[[menu.main]]
name = "Nomineringar 2025"
url = "/nomineringar/nomineringar2025/"
weight = 2
parent = "Nomineringar"

  [[menu.main]]
  name = "Omröstningar"
  url = "/lankar/"
  weight = 5

[[menu.main]]
name = "Vinnare"
url = ""          # Ingen indexsida
weight = 6
identifier = "vinnare"

[[menu.main]]
name = "Vinnare 2024"
url = "/vinnare/vinnare2024/"
weight = 1
parent = "vinnare"

[[menu.main]]
name = "Vinnare 2025"
url = "/vinnare/vinnare2025/"
weight = 2
parent = "vinnare"

[languages]

  [languages.sv]
  languageName = "Svenska"
  languageCode = "sv"
  weight = 1
  title = "SERIEFOLKETS STORA PRIS"

[params]
  colorscheme = "cyan"
  customCSS = ["css/custom.css"]