baseURL = 'https://seriefolkets-stora-pris.vercel.app'
languageCode = 'sv-se'
title = 'SERIEFOLKETS STORA PRIS'
theme = 'blowfish'
defaultContentLanguage = "sv"
defaultContentLanguageInSubdir = false

[menu]

  [[menu.main]]
  name = "Om priset"
  url = "/about/"
  weight = 1

  [[menu.main]]
  name = "Kategorier"
  url = "/kategorier/"
  weight = 2

  [[menu.main]]
  name = "Omr√∂stningar 2025"
  url = "/lankar/"
  weight = 3

  [[menu.main]]
  name = "Vinnare"
  url = "/vinnare/"
  weight = 4

    [[menu.main]]
    name = "Vinnare 2024"
    url = "/vinnare/vinnare2024/"
    weight = 1
    parent = "Vinnare"

    [[menu.main]]
    name = "Vinnare 2025"
    url = "/vinnare/vinnare2025/"
    weight = 2
    parent = "Vinnare"



[languages]

  [languages.sv]
  languageName = "Svenska"
  languageCode = "sv"
  weight = 1
  title = "SERIEFOLKETS STORA PRIS"