baseURL = 'https://seriefolkets-stora-pris.vercel.app'
languageCode = 'sv-se'
title = 'SERIEFOLKETS STORA PRIS'
theme = 'blowfish'
defaultContentLanguage = "sv"
defaultContentLanguageInSubdir = false

[menu]

  [[menu.main]]
  name = "Om priset"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Kategorier"
  url = "/kategorier/"
  weight = 3

  [[menu.main]]
  name = "Omr√∂stningar 2025"
  url = "/lankar/"
  weight = 4

   [[menu.main]]
  name = "Vinnare 2024"
  url = "/vinnare2024/"
  weight = 5

[languages]

  [languages.sv]
  languageName = "Svenska"
  languageCode = "sv"
  weight = 1
  title = "SERIEFOLKETS STORA PRIS"