baseURL = 'https://seriefolkets-stora-pris.vercel.app'
languageCode = 'sv-se'
title = 'SERIEFOLKETS STORA PRIS'
theme = 'blowfish'
defaultContentLanguage = "sv"
defaultContentLanguageInSubdir = false

[menu]

 [[menu.main]]
  name = "Logg"
  identifier = "Logg"  
  weight = 1

  [[menu.main]]
  name = "Vinnarfoton"
  url = "/logg/foton2024/"
  weight = 1
  parent = "Logg"


  [[menu.main]]
  name = "Frågor"
  url = "/fragor/"
  weight = 2

  [[menu.main]]
  name = "Kategorier"
  url = "/kategorier/"
  weight = 3

[[menu.main]]
name = "Nomineringar"
weight = 4
identifier = "Nomineringar"

    [[menu.main]]
    name = "Nomineringar 2024"
    url = "/nomineringar/2024/"
    weight = 1
    parent = "Nomineringar"

    [[menu.main]]
    name = "Nomineringar 2025"
    url = "/nomineringar/2025/"
    weight = 2
    parent = "Nomineringar"

[[menu.main]]
name = "Omröstningar"
url = "/lankar/"
weight = 5

[[menu.main]]
name = "Vinnare"
weight = 6
identifier = "vinnare"

    [[menu.main]]
    name = "Vinnare 2024"
    url = "/vinnare/2024/"
    weight = 1
    parent = "vinnare"

    [[menu.main]]
    name = "Vinnare 2025"
    url = "/vinnare/2025/"
    weight = 2
    parent = "vinnare"

[languages]

  [languages.sv]
  languageName = "Svenska"
  languageCode = "sv"
  weight = 1
  title = "SERIEFOLKETS STORA PRIS"

[params]
  colorscheme = "cyan"
  customCSS = ["css/custom.css"]