baseURL = 'https://seriefolkets-stora-pris.vercel.app'
languageCode = 'sv-se'
title = 'SERIEFOLKETS STORA PRIS'
theme = 'blowfish'

[menu]

  [[menu.main]]
  name = "Om priset"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Kategorier"
  url = "/kategorier/"
  weight = 3

  [[menu.main]]
  name = "Omr√∂stningar 2025"
  url = "/lankar/"
  weight = 4

   [[menu.main]]
  name = "Vinnare 2024"
  url = "/vinnare2024/"
  weight = 5